# Generated by Django 3.2.12 on 2022-08-04 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('team', '0003_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('fileID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('file_image', models.CharField(max_length=50, null=True)),
                ('file_name', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_visit_time', models.DateTimeField(auto_now=True)),
                ('data', models.TextField(default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('type', models.IntegerField(choices=[(0, 'root'), (1, 'project'), (2, 'directory'), (12, 'uml'), (13, 'prototype'), (14, 'text')])),
                ('father', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='file.file')),
                ('file_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
        ),
    ]
