# Generated by Django 4.0.4 on 2022-08-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='abandon_time',
            field=models.DateTimeField(null=True),
        ),
    ]
