# Generated by Django 4.0.4 on 2022-08-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_file_abandon_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.IntegerField(choices=[(0, 'root'), (1, 'project'), (2, 'directory'), (12, 'uml'), (13, 'prototype'), (14, 'text'), (15, 'text_template')]),
        ),
    ]
