# Generated by Django 4.0.4 on 2022-08-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_share'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('imageID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('fileID', models.IntegerField(null=True)),
                ('preview_image', models.CharField(max_length=1000, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
