# Generated by Django 4.0.4 on 2022-08-10 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_password_alter_user_summary'),
        ('file', '0005_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='lock_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='上锁的用户', to='user.user'),
        ),
    ]
