# Generated by Django 4.0.4 on 2022-08-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0006_file_lock_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='lock_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
