# Generated by Django 3.2.12 on 2022-08-04 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('team', '0003_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='root_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xx', to='file.file'),
        ),
    ]
