# Generated by Django 4.0.4 on 2022-08-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_team_root_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamID',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='团队ID'),
        ),
    ]
