# Generated by Django 4.0.4 on 2022-08-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_team_teamid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='invite_url',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='user',
        ),
        migrations.AddField(
            model_name='invitation',
            name='invite_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
