# Generated by Django 4.0.4 on 2022-08-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_remove_invitation_invite_url_remove_invitation_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
