# Generated by Django 3.2.12 on 2022-08-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_invitation_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_user',
            name='authority',
            field=models.IntegerField(choices=[(2, 'founder'), (1, 'manager'), (0, 'member')], default=0),
        ),
    ]
