# Generated by Django 4.0.4 on 2022-08-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=1000, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='summary',
            field=models.CharField(max_length=1000, null=True, verbose_name='个人资料'),
        ),
    ]
