# Generated by Django 4.0.6 on 2022-07-31 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
